@startuml aws_architecture
' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/EC2.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Database/RDS.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AvailabilityZone.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!include AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml

top to bottom direction
hide stereotype
skinparam linetype ortho

title AWS Architecture case2

actor "User" as user
component "Another system" as another_system
AWSCloudGroup(cloud) {
  VPCGroup(vpc, "virtual private cloud (10.0.0.0/16)") {
    VPCInternetGateway(internet_gateway, "internet gateway", "") #Transparent
    ElasticLoadBalancingApplicationLoadBalancer(alb, "Application Load Balancer", "") #Transparent
    user -d-> internet_gateway : HTTP
    another_system <.d. internet_gateway : HTTP
    internet_gateway -d-> alb
    AvailabilityZoneGroup(az_1, "\tap-northeast-1a\t") {
      PublicSubnetGroup(az_1_public, "public subnet\n(10.0.0.0/24)") {
        VPCNATGateway(az_1_nat_gateway, "NAT gateway", "") #Transparent
      }
      PrivateSubnetGroup(az_1_private, "private subnet\n(10.0.10.0/24)") {
        EC2Instance(az_1_pr_ec2, "EC2", "") #Transparent
        RDS(az_1_rds_1, "RDS", "mysql") #Transparent
      }
      alb -d-> az_1_pr_ec2
      az_1_pr_ec2 -l-> az_1_rds_1
      az_1_pr_ec2 .u.> az_1_nat_gateway
      az_1_nat_gateway .u.> internet_gateway
    }

    AvailabilityZoneGroup(az_2, "\tap-northeast-1c\t") {
      PublicSubnetGroup(az_2_public, "public subnet\n(10.0.1.0/24)") {
        VPCNATGateway(az_2_nat_gateway, "NAT gateway", "") #Transparent
      }
      PrivateSubnetGroup(az_2_private, "private subne\n(10.0.11.0/24)") {
        EC2Instance(az_2_pr_ec2, "EC2", "") #Transparent
        RDS(az_2_rds_1, "RDS", "mysql") #Transparent
      }

      alb -d-> az_2_pr_ec2
      az_2_pr_ec2 -r-> az_2_rds_1
      az_2_pr_ec2 .u.> az_2_nat_gateway
      az_2_nat_gateway .u.> internet_gateway
    }

    ' az_1_public -[hidden]d- az_2_public
    ' az_1_private -[hidden]d- az_2_private
  }
}
@enduml